# Generated by Django 2.1.1 on 2018-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_netto', models.FloatField()),
                ('waktu_pjb', models.FloatField()),
                ('waktu_recieving', models.FloatField()),
                ('waktu_verify', models.FloatField()),
                ('waktu_transfer', models.FloatField()),
                ('waktu_payment', models.FloatField()),
                ('waktu_po', models.FloatField()),
                ('biaya_pekerja', models.FloatField()),
                ('biaya_material', models.FloatField()),
                ('jadwal_berubah', models.BooleanField()),
                ('jumlah_hari_berubah', models.FloatField()),
                ('correct_packaging', models.BooleanField()),
                ('correct_content', models.BooleanField()),
                ('tanggal_penerimaan', models.TimeField(auto_now=True)),
            ],
        ),
    ]
