# Generated by Django 2.1.1 on 2018-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20180928_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrik', models.TextField()),
                ('lw', models.FloatField()),
                ('gw', models.FloatField()),
            ],
        ),
    ]
