# Generated by Django 2.1.1 on 2018-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_metrik'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrik',
            name='smax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='metrik',
            name='smin',
            field=models.FloatField(default=0),
        ),
    ]
