# Generated by Django 2.1.1 on 2018-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20181007_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.FloatField()),
                ('total_forcasted_sourcing_target', models.FloatField()),
                ('total_rice_product_needed', models.FloatField()),
                ('planning_cycle_time', models.FloatField()),
                ('total_cost_of_goods_sold_a_year', models.FloatField()),
                ('inventory_on_hand', models.FloatField()),
            ],
        ),
    ]
