# Generated by Django 2.1.1 on 2018-10-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_annualdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualdata',
            options={'verbose_name_plural': 'Annual Data'},
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='waktu_pjb',
        ),
    ]
